apiVersion: v1
kind: Service 
metadata:
  name: ext-service
  labels:
    name: ext-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30000
  selector:
    app: moodle
    tier: frontend